/**
 * Builds the Apps Script web-app bundle: Vite for the client, esbuild for
 * the server, then HTML that inlines both for `HtmlService`.
 *
 * Ported verbatim from the per-consumer `scripts/build.mjs` (create-gas-kit
 * issue #2) — every consumer carried its own copy, and this behaviour is
 * already verified against a real deployment, so escaping rules and output
 * names must not drift even slightly while moving.
 *
 * `HtmlService` parses inline `<script>`/`<style>` blocks as HTML text before
 * the browser ever sees them, so a stray `</script>` or `</style>` inside a
 * string literal closes the tag early. `escapeJsForGas` / `escapeCssForGas`
 * exist only for that. Backticks and `://` get the same treatment because
 * GAS's HTML sanitizer independently mangles both.
 *
 * `vite` and `esbuild` are optional peers, loaded with a dynamic `import()`
 * only once this function actually runs — nothing else in gas-app-kit needs
 * either at load time, so a consumer who never calls `buildWebApp` never
 * needs to install them.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'

import { EnvsError } from './envs.ts'
import { DEFAULT_BUILD_DIR } from './project.ts'
import { collectBuildInfo, type BuildInfo } from './version.ts'
import { createUI } from './ui.mjs'

export interface BuildWebAppOptions {
  cwd?: string
  env?: string
  buildDir?: string
  distDir?: string
  serverEntry?: string
}

export interface BuildWebAppResult {
  buildDir: string
  files: string[]
}

/** GAS's V8 runtime executes the bundle as a plain script, not a module. */
export function stripGasSyntax(code: string): string {
  return code
    .replace(/export\s*\{[\s\S]*?\}\s*;?\s*/g, '')
    .replace(/^export\s+/gm, '')
    .replace(/^import\s+.*$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
}

/** Escape what HtmlService's inline `<script>` parsing would otherwise break. */
export function escapeJsForGas(js: string): string {
  let out = js.replace(/<\/script\s*>/gi, '<\\/script>')
  out = out.replace(/:\/\//g, ':\\u002F\\u002F')
  return out
}

/** Same idea for the inline `<style>` block. */
export function escapeCssForGas(css: string): string {
  return css.replace(/<\/style\s*>/gi, '\\3C/style>')
}

export function renderBanner(info: BuildInfo): string {
  return `/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by gas-app-kit buildWebApp.
 *
 * version : ${info.version}
 * commit  : ${info.commit}${info.dirty ? ' (dirty)' : ''}
 * branch  : ${info.branch}
 * env     : ${info.env}
 * builtAt : ${info.builtAt}
 */
`
}

export function renderIndexHtml(css: string): string {
  const safeCss = escapeCssForGas(css)
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>${safeCss}</style>
</head>
<body>
  <div id="app"></div>
  <?!= include('app') ?>
</body>
</html>`
}

/**
 * Vite build, then the same post-processing the reference script ran:
 * disable template literals during the esbuild transform, then escape every
 * remaining backtick — belt and suspenders against HtmlService mangling one.
 */
async function buildClient(root: string, dist: string, distDir: string): Promise<void> {
  try {
    const { build } = await import('vite')
    await build({
      root,
      build: {
        outDir: distDir,
        emptyOutDir: true,
        cssCodeSplit: false,
        modulePreload: false,
        assetsInlineLimit: 1e9,
        rollupOptions: {
          output: {
            // `codeSplitting` is a Vite 8 (rolldown) output option that the
            // installed vite types may not declare yet.
            codeSplitting: false,
            entryFileNames: 'app.js',
            assetFileNames: 'app.[ext]',
          } as Record<string, unknown>,
        },
      },
    })
  } catch (err) {
    throw new EnvsError(`Client build failed: ${(err as Error).message}`)
  }

  const file = path.join(dist, 'app.js')
  try {
    const { transform } = await import('esbuild')
    const { code } = await transform(fs.readFileSync(file, 'utf-8'), {
      supported: { 'template-literal': false },
    })
    fs.writeFileSync(file, code.replaceAll('`', '\\u0060'))
  } catch (err) {
    throw new EnvsError(`Client build failed: ${(err as Error).message}`)
  }
}

async function buildServer(root: string, buildDir: string, serverEntry: string, info: BuildInfo): Promise<void> {
  let text: string
  try {
    const { build } = await import('esbuild')
    const result = await build({
      entryPoints: [path.join(root, serverEntry)],
      bundle: true,
      format: 'esm',
      target: ['es2019'],
      write: false,
    })
    const outputFile = result.outputFiles[0]
    if (!outputFile) throw new Error('esbuild produced no output file')
    text = outputFile.text
  } catch (err) {
    throw new EnvsError(`Server build failed: ${(err as Error).message}`)
  }

  const code = stripGasSyntax(text)
  fs.writeFileSync(path.join(buildDir, 'Code.gs'), renderBanner(info) + '\n' + code)
}

function generateHtml(dist: string, buildDir: string): void {
  const cssPath = path.join(dist, 'app.css')
  const css = fs.existsSync(cssPath) ? fs.readFileSync(cssPath, 'utf-8') : ''
  const js = escapeJsForGas(fs.readFileSync(path.join(dist, 'app.js'), 'utf-8'))

  fs.writeFileSync(path.join(buildDir, 'index.html'), renderIndexHtml(css))
  fs.writeFileSync(path.join(buildDir, 'app.html'), `<script>${js}</script>`)
}

function copyAppsScript(root: string, buildDir: string): void {
  fs.copyFileSync(path.join(root, 'appsscript.json'), path.join(buildDir, 'appsscript.json'))
}

/**
 * Build the web-app bundle: client (Vite), server (esbuild), HTML, manifest.
 * Errors from vite/esbuild are wrapped so they name the step that failed —
 * this is a library call, so it throws rather than printing and exiting.
 */
export async function buildWebApp(options: BuildWebAppOptions = {}): Promise<BuildWebAppResult> {
  const {
    cwd = process.cwd(),
    env = process.env.BUILD_ENV ?? 'local',
    buildDir: buildDirName = DEFAULT_BUILD_DIR,
    distDir = 'dist',
    serverEntry = 'src/server/index.ts',
  } = options

  const dist = path.join(cwd, distDir)
  const buildDir = path.join(cwd, buildDirName)
  fs.mkdirSync(dist, { recursive: true })
  fs.mkdirSync(buildDir, { recursive: true })

  const ui = createUI('build')
  ui.banner()
  ui.setTotal(4)
  const info = collectBuildInfo({ env, cwd })

  ui.step('Client')
  await buildClient(cwd, dist, distDir)
  ui.item('client bundled')

  ui.step('Server')
  await buildServer(cwd, buildDir, serverEntry, info)
  ui.item('server bundled -> Code.gs')

  ui.step('HTML')
  generateHtml(dist, buildDir)
  ui.item('index.html + app.html generated')

  ui.step('Manifest')
  copyAppsScript(cwd, buildDir)
  ui.item('appsscript.json copied')

  ui.done(`Build complete -> ${buildDir}`)

  return { buildDir, files: ['Code.gs', 'index.html', 'app.html', 'appsscript.json'] }
}
